version: '3.5' #specify  docker-compose version

services:
  angular-service:
    container_name: angular-container
    build : ./
    volumes:
    - './:/usr/sc/app'
    ports:
      - '4201:4200'
    command: >
      bash -c "npm start"