version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=passer1234
      - MYSQL_DATABASE=testingManageBack
      - MYSQL_USER=dave
      - MYSQL_PASSWORD=passer1234
    ports:
      - 51.77.132.116:33061:33061
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 51.77.132.116:9092:9092
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone